substitutions:
  name: daly-bms-ble
  bms0: "${name} bms0"
  bms1: "${name} bms1"
  device_description: "Monitor a DALY Battery Management System via BLE"
  external_components_source: github://syssi/esphome-daly-bms@main
  bms0_mac_address: !secret bms0_mac_address
  bms1_mac_address: !secret bms1_mac_address

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-daly-bms"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

daly_bms_ble:
  - ble_client_id: client0
    id: bms0
    password: 12345678
    update_interval: 10s
  - ble_client_id: client1
    id: bms1
    password: 12345678
    update_interval: 10s

binary_sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

button:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    # Retrieves the BMS settings and prints them in the ESPHome logs
    retrieve_settings:
      name: "${bms0} retrieve settings"
    # Restarts the BMS
    restart:
      name: "${bms0} restart"
    # Shuts down the BMS
    shutdown:
      name: "${bms0} shutdown"
    # Resets the BMS to the factory settings
    factory_reset:
      name: "${bms0} factory reset"
    # Resets the BMS current to zero
    reset_current:
      name: "${bms0} reset current"

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    retrieve_settings:
      name: "${bms1} retrieve settings"
    restart:
      name: "${bms1} restart"
    shutdown:
      name: "${bms1} shutdown"
    factory_reset:
      name: "${bms1} factory reset"
    reset_current:
      name: "${bms1} reset current"

sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    error_bitmask:
      name: "${bms0} error bitmask"
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    state_of_charge:
      name: "${bms0} state of charge"
    charging_cycles:
      name: "${bms0} charging cycles"
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    temperature_1:
      name: "${bms0} temperature 1"
    temperature_2:
      name: "${bms0} temperature 2"
    temperature_3:
      name: "${bms0} temperature 3"
    temperature_4:
      name: "${bms0} temperature 4"
    temperature_5:
      name: "${bms0} temperature 5"
    temperature_6:
      name: "${bms0} temperature 6"
    temperature_7:
      name: "${bms0} temperature 7"
    temperature_8:
      name: "${bms0} temperature 8"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
    cell_voltage_9:
      name: "${bms0} cell voltage 9"
    cell_voltage_10:
      name: "${bms0} cell voltage 10"
    cell_voltage_11:
      name: "${bms0} cell voltage 11"
    cell_voltage_12:
      name: "${bms0} cell voltage 12"
    cell_voltage_13:
      name: "${bms0} cell voltage 13"
    cell_voltage_14:
      name: "${bms0} cell voltage 14"
    cell_voltage_15:
      name: "${bms0} cell voltage 15"
    cell_voltage_16:
      name: "${bms0} cell voltage 16"
    cell_count:
      name: "${bms0} cell count"
    temperature_sensors:
      name: "${bms0} temperature sensors"
    capacity_remaining:
      name: "${bms0} capacity remaining"

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    error_bitmask:
      name: "${bms1} error bitmask"
    total_voltage:
      name: "${bms1} total voltage"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    state_of_charge:
      name: "${bms1} state of charge"
    charging_cycles:
      name: "${bms1} charging cycles"
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    temperature_1:
      name: "${bms1} temperature 1"
    temperature_2:
      name: "${bms1} temperature 2"
    temperature_3:
      name: "${bms1} temperature 3"
    temperature_4:
      name: "${bms1} temperature 4"
    temperature_5:
      name: "${bms1} temperature 5"
    temperature_6:
      name: "${bms1} temperature 6"
    temperature_7:
      name: "${bms1} temperature 7"
    temperature_8:
      name: "${bms1} temperature 8"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
    cell_voltage_9:
      name: "${bms1} cell voltage 9"
    cell_voltage_10:
      name: "${bms1} cell voltage 10"
    cell_voltage_11:
      name: "${bms1} cell voltage 11"
    cell_voltage_12:
      name: "${bms1} cell voltage 12"
    cell_voltage_13:
      name: "${bms1} cell voltage 13"
    cell_voltage_14:
      name: "${bms1} cell voltage 14"
    cell_voltage_15:
      name: "${bms1} cell voltage 15"
    cell_voltage_16:
      name: "${bms1} cell voltage 16"
    cell_count:
      name: "${bms1} cell count"
    temperature_sensors:
      name: "${bms1} temperature sensors"
    capacity_remaining:
      name: "${bms1} capacity remaining"

text_sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    battery_status:
      name: "${bms0} battery status"
    errors:
      name: "${bms0} errors"

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    battery_status:
      name: "${bms1} battery status"
    errors:
      name: "${bms1} errors"

switch:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    balancer:
      name: "${bms0} balancer"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    balancer:
      name: "${bms1} balancer"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${bms0} enable bluetooth connection"

  - platform: ble_client
    ble_client_id: client1
    id: ble_client_switch1
    name: "${bms1} enable bluetooth connection"
