substitutions:
  name: daly-bms-ble
  bms0: "${name} bms0"
  bms1: "${name} bms1"
  device_description: "Monitor a DALY Battery Management System via BLE"
  external_components_source: github://syssi/esphome-daly-bms@main
  bms0_mac_address: !secret bms0_mac_address
  bms1_mac_address: !secret bms1_mac_address

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-daly-bms"
    version: 1.1.0

  devices:
    - id: device0
      name: "${bms0}"
    - id: device1
      name: "${bms1}"

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - switch.turn_off: ble_client_switch1
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

daly_bms_ble:
  - ble_client_id: client0
    id: bms0
    password: 12345678
    update_interval: 10s
  - ble_client_id: client1
    id: bms1
    password: 12345678
    update_interval: 10s

binary_sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
      device_id: device0
    charging:
      name: "${bms0} charging"
      device_id: device0
    discharging:
      name: "${bms0} discharging"
      device_id: device0

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
      device_id: device1
    charging:
      name: "${bms1} charging"
      device_id: device1
    discharging:
      name: "${bms1} discharging"
      device_id: device1

button:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    # Retrieves the BMS settings and prints them in the ESPHome logs
    retrieve_settings:
      name: "${bms0} retrieve settings"
      device_id: device0
    # Restarts the BMS
    restart:
      name: "${bms0} restart"
      device_id: device0
    # Shuts down the BMS
    shutdown:
      name: "${bms0} shutdown"
      device_id: device0
    # Resets the BMS to the factory settings
    factory_reset:
      name: "${bms0} factory reset"
      device_id: device0
    # Resets the BMS current to zero
    reset_current:
      name: "${bms0} reset current"
      device_id: device0

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    retrieve_settings:
      name: "${bms1} retrieve settings"
      device_id: device1
    restart:
      name: "${bms1} restart"
      device_id: device1
    shutdown:
      name: "${bms1} shutdown"
      device_id: device1
    factory_reset:
      name: "${bms1} factory reset"
      device_id: device1
    reset_current:
      name: "${bms1} reset current"
      device_id: device1

sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    error_bitmask:
      name: "${bms0} error bitmask"
      device_id: device0
    total_voltage:
      name: "${bms0} total voltage"
      device_id: device0
    current:
      name: "${bms0} current"
      device_id: device0
    power:
      name: "${bms0} power"
      device_id: device0
    charging_power:
      name: "${bms0} charging power"
      device_id: device0
    discharging_power:
      name: "${bms0} discharging power"
      device_id: device0
    state_of_charge:
      name: "${bms0} state of charge"
      device_id: device0
    charging_cycles:
      name: "${bms0} charging cycles"
      device_id: device0
    min_cell_voltage:
      name: "${bms0} min cell voltage"
      device_id: device0
    max_cell_voltage:
      name: "${bms0} max cell voltage"
      device_id: device0
    min_voltage_cell:
      name: "${bms0} min voltage cell"
      device_id: device0
    max_voltage_cell:
      name: "${bms0} max voltage cell"
      device_id: device0
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
      device_id: device0
    average_cell_voltage:
      name: "${bms0} average cell voltage"
      device_id: device0
    temperature_1:
      name: "${bms0} temperature 1"
      device_id: device0
    temperature_2:
      name: "${bms0} temperature 2"
      device_id: device0
    temperature_3:
      name: "${bms0} temperature 3"
      device_id: device0
    temperature_4:
      name: "${bms0} temperature 4"
      device_id: device0
    temperature_5:
      name: "${bms0} temperature 5"
      device_id: device0
    temperature_6:
      name: "${bms0} temperature 6"
      device_id: device0
    temperature_7:
      name: "${bms0} temperature 7"
      device_id: device0
    temperature_8:
      name: "${bms0} temperature 8"
      device_id: device0
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
      device_id: device0
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
      device_id: device0
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
      device_id: device0
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
      device_id: device0
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
      device_id: device0
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
      device_id: device0
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
      device_id: device0
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
      device_id: device0
    cell_voltage_9:
      name: "${bms0} cell voltage 9"
      device_id: device0
    cell_voltage_10:
      name: "${bms0} cell voltage 10"
      device_id: device0
    cell_voltage_11:
      name: "${bms0} cell voltage 11"
      device_id: device0
    cell_voltage_12:
      name: "${bms0} cell voltage 12"
      device_id: device0
    cell_voltage_13:
      name: "${bms0} cell voltage 13"
      device_id: device0
    cell_voltage_14:
      name: "${bms0} cell voltage 14"
      device_id: device0
    cell_voltage_15:
      name: "${bms0} cell voltage 15"
      device_id: device0
    cell_voltage_16:
      name: "${bms0} cell voltage 16"
      device_id: device0
    cell_count:
      name: "${bms0} cell count"
      device_id: device0
    temperature_sensors:
      name: "${bms0} temperature sensors"
      device_id: device0
    capacity_remaining:
      name: "${bms0} capacity remaining"
      device_id: device0

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    error_bitmask:
      name: "${bms1} error bitmask"
      device_id: device1
    total_voltage:
      name: "${bms1} total voltage"
      device_id: device1
    current:
      name: "${bms1} current"
      device_id: device1
    power:
      name: "${bms1} power"
      device_id: device1
    charging_power:
      name: "${bms1} charging power"
      device_id: device1
    discharging_power:
      name: "${bms1} discharging power"
      device_id: device1
    state_of_charge:
      name: "${bms1} state of charge"
      device_id: device1
    charging_cycles:
      name: "${bms1} charging cycles"
      device_id: device1
    min_cell_voltage:
      name: "${bms1} min cell voltage"
      device_id: device1
    max_cell_voltage:
      name: "${bms1} max cell voltage"
      device_id: device1
    min_voltage_cell:
      name: "${bms1} min voltage cell"
      device_id: device1
    max_voltage_cell:
      name: "${bms1} max voltage cell"
      device_id: device1
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
      device_id: device1
    average_cell_voltage:
      name: "${bms1} average cell voltage"
      device_id: device1
    temperature_1:
      name: "${bms1} temperature 1"
      device_id: device1
    temperature_2:
      name: "${bms1} temperature 2"
      device_id: device1
    temperature_3:
      name: "${bms1} temperature 3"
      device_id: device1
    temperature_4:
      name: "${bms1} temperature 4"
      device_id: device1
    temperature_5:
      name: "${bms1} temperature 5"
      device_id: device1
    temperature_6:
      name: "${bms1} temperature 6"
      device_id: device1
    temperature_7:
      name: "${bms1} temperature 7"
      device_id: device1
    temperature_8:
      name: "${bms1} temperature 8"
      device_id: device1
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
      device_id: device1
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
      device_id: device1
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
      device_id: device1
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
      device_id: device1
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
      device_id: device1
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
      device_id: device1
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
      device_id: device1
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
      device_id: device1
    cell_voltage_9:
      name: "${bms1} cell voltage 9"
      device_id: device1
    cell_voltage_10:
      name: "${bms1} cell voltage 10"
      device_id: device1
    cell_voltage_11:
      name: "${bms1} cell voltage 11"
      device_id: device1
    cell_voltage_12:
      name: "${bms1} cell voltage 12"
      device_id: device1
    cell_voltage_13:
      name: "${bms1} cell voltage 13"
      device_id: device1
    cell_voltage_14:
      name: "${bms1} cell voltage 14"
      device_id: device1
    cell_voltage_15:
      name: "${bms1} cell voltage 15"
      device_id: device1
    cell_voltage_16:
      name: "${bms1} cell voltage 16"
      device_id: device1
    cell_count:
      name: "${bms1} cell count"
      device_id: device1
    temperature_sensors:
      name: "${bms1} temperature sensors"
      device_id: device1
    capacity_remaining:
      name: "${bms1} capacity remaining"
      device_id: device1

switch:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    balancer:
      name: "${bms0} balancer"
      device_id: device0
    charging:
      name: "${bms0} charging"
      device_id: device0
    discharging:
      name: "${bms0} discharging"
      device_id: device0

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    balancer:
      name: "${bms1} balancer"
      device_id: device1
    charging:
      name: "${bms1} charging"
      device_id: device1
    discharging:
      name: "${bms1} discharging"
      device_id: device1

  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"
    id: ble_client_switch0
    device_id: device0

  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"
    id: ble_client_switch1
    device_id: device1

text_sensor:
  - platform: daly_bms_ble
    daly_bms_ble_id: bms0
    battery_status:
      name: "${bms0} battery status"
      device_id: device0
    errors:
      name: "${bms0} errors"
      device_id: device0

  - platform: daly_bms_ble
    daly_bms_ble_id: bms1
    battery_status:
      name: "${bms1} battery status"
      device_id: device1
    errors:
      name: "${bms1} errors"
      device_id: device1
